name: Generate Index HTML 

on:
  push:
    branches: [ "main" ]

jobs:
  generate-index:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4 

      - name: Generate supindex.html 
        run: |
          cat << EOF > supindex.html 
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Super Index</title>
              <style>
                  :root {
                      --bg-color: #0d1117;
                      --text-color: #c9d1d9;
                      --border-color: #30363d;
                      --link-color: #58a6ff;
                  }
 
                  body {
                      background-color: var(--bg-color);
                      color: var(--text-color);
                      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                      margin: 2em auto;
                      max-width: 800px;
                      padding: 0 20px;
                  }

                  .file-list {
                      border: 1px solid var(--border-color);
                      border-radius: 6px;
                      list-style: none;
                      padding: 0;
                  }

                  .file-item {
                      padding: 8px 16px;
                      border-bottom: 1px solid var(--border-color);
                      display: flex;
                      align-items: center;
                  }

                  .file-item:last-child {
                      border-bottom: none;
                  }

                  .file-item a {
                      color: var(--link-color);
                      text-decoration: none;
                  }

                  .file-item a:hover {
                      text-decoration: underline;
                  }
              </style>
          </head>
          <body>
              <h1>Files Index</h1>
              <ul class="file-list">
                  $(find . -type f ! -path './.git/*' ! -name 'supindex.html' ! -name '.gitignore' ! -name 'LICENSE' ! -name 'README.md' ! -path './.github/*' -printf '<li class="file-item"><a href="%P">%P</a></li>\n')
              </ul>
          </body>
          </html>
           

      - name: Commit and push 
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add supindex.html 
          git commit -m "Auto-generated index file" || echo "No changes to commit"
          git push