name: Generate Index HTML 
 
on:
  push: 
    branches: [ "main" ]
 
jobs:
  generate-index:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4 
 
      - name: Generate supindex.html 
        run: | 
          cat << EOF > supindex.html 
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
              <title>Web Index</title>
              <style>
                  /* 样式代码 */
              </style> 
          </head>
          <body>
              <h1>Files Index</h1>
              <ul class="file-list">
                  $$(find . -type f ! -path './.git/*' ! -name 'supindex.html' ! -name '.gitignore' ! -name 'LICENSE' ! -name 'README.md' ! -path './.github/*' -printf '<li class="file-item"><a href="%P">%P</a></li>\n')
              </ul>
          </body> 
          </html>
          EOF 
 
      - name: Commit and push 
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add supindex.html 
          git commit -m "Auto-generated index file" || echo "No changes to commit"
          git push